# importing panda for the task
import pandas as pd


# Read data from CSV file
# created a decent size dataset to show the working of the python script
def read_data(file_path):
    return pd.read_csv("orders.csv")


# Computes total revenue generated by the online store for each month
def revenue_per_month(data):
    # Converts 'order_date' to datetime with the correct format as the 'order_date' as it will be in string format.
    data["order_date"] = pd.to_datetime(data["order_date"], format="%d-%m-%Y")
    # Extracts year and month from the order_date for further analysis by grouping it based on month.
    data["month"] = data["order_date"].dt.to_period("M")
    return data.groupby("month")["total_price"].sum()


# similarly , group by groups the attributes for specific operations
# Compute total revenue generated by each product
def revenue_per_product(data):
    return data.groupby("product_name")["total_price"].sum()


# Compute total revenue generated by each customer
def revenue_per_customer(data):
    return data.groupby("customer_id")["total_price"].sum()


# Identify the top 10 customers by revenue generated by them
def top_10_customers(data):
    return revenue_per_customer(data).nlargest(10)


# Main function to run all tasks
def main():
    file_path = "C:/Users/Prajin/yield/orders.csv"  # mentioned the complete directory for the ease of user review
    data = read_data(file_path)
    data["total_price"] = data["product_price"] * data["quantity"]

    print("Revenue per month:")
    print(revenue_per_month(data))

    print("\nRevenue per product:")
    print(revenue_per_product(data))

    print("\nRevenue per customer:")
    print(revenue_per_customer(data))

    print("\nTop 10 customers by revenue:")
    print(top_10_customers(data))


if __name__ == "__main__":
    main()
